// PracticeRecord ID generator — T013.4A0_RECORDING_SAVE_FOUNDATION.
//
// ID ownership contract (Chief Architect ruling, T013.4A0):
// - `PracticeRecord.id` MUST be a UUID v4 string.
// - The Repository layer DOES NOT generate IDs. It only validates
//   that the supplied `id` is non-empty and persists it verbatim.
// - IDs are generated by the application / use-case layer BEFORE
//   calling `PracticeRecordRepository.insert(...)`.
// - This keeps the Repository a pure persistence boundary and lets
//   callers (T013.4A and beyond) decide whether to mint a fresh
//   UUID, reuse a deterministic id for a "re-save" flow, or stub
//   one in for tests.
//
// Why a dedicated abstraction (rather than calling `Uuid().v4()`
// inline):
// - Tests need to override the generator with a deterministic
//   implementation that returns a fixed id, so the saved
//   `PracticeRecord.id` can be asserted byte-for-byte.
// - Future flows (offline replay, idempotent re-save, sync) may
//   need to mint ids from a different source. Keeping the surface
//   small and abstract means we never reach into the package
//   directly from a Controller / use-case.
//
// Implementation notes:
// - The default uses `package:uuid/uuid.dart`'s `Uuid.v4()` —
//   RFC 4122 variant 1, version 4.
// - The `Uuid` instance is reused across calls; `Uuid()` is a thin
//   wrapper around a `Random` and is safe to share.
// - We never hand-roll a 32-char hex id, never concatenate
//   timestamps, never call `Random.secure()` ourselves — every
//   shortcut has bitten us in similar systems (collision risk,
//   version-nibble drift, variant-bit mistakes).
// - This generator MUST NOT touch the Repository, the database,
//   the Riverpod scope, or any UI layer. It is pure.

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

/// Strategy interface for minting [PracticeRecord.id] values.
///
/// Implementations MUST return a UUID v4 string. Tests typically
/// override the provider with [_FakePracticeRecordIdGenerator] (see
/// the test file) to pin the id.
abstract interface class PracticeRecordIdGenerator {
  /// Returns a freshly minted UUID v4 string.
  String generate();
}

/// Default [PracticeRecordIdGenerator] backed by `package:uuid`.
///
/// Internally holds a single [Uuid] instance so the underlying
/// `Random` source is reused across calls.
class UuidPracticeRecordIdGenerator implements PracticeRecordIdGenerator {
  UuidPracticeRecordIdGenerator({Uuid? uuid}) : _uuid = uuid ?? const Uuid();

  final Uuid _uuid;

  @override
  String generate() => _uuid.v4();
}

/// Riverpod provider for the default
/// [PracticeRecordIdGenerator]. Tests can override this with
/// `_FakePracticeRecordIdGenerator` (or any other implementation) to
/// pin the id for assertions.
final Provider<PracticeRecordIdGenerator> practiceRecordIdGeneratorProvider =
    Provider<PracticeRecordIdGenerator>(
  (Ref ref) => UuidPracticeRecordIdGenerator(),
);
