// PracticeRecords table.
//
// T013.1 scope:
// - Schema-only. No DAO, no Repository, no CRUD methods on this class —
//   Repository / DAO layers are introduced in T013.2 and later.
// - Field set mirrors `docs/DATA_MODEL_DRAFT.md` §13.1 verbatim. The
//   architecture decision "PracticeRecordData (Drift) vs PracticeRecord
//   (domain/freezed) must not share a name" (DATA_MODEL_DRAFT.md §13.1
//   命名约定) is enforced by `@DataClassName('PracticeRecordData')`.
// - The generated row class will be `PracticeRecordData`; the future
//   domain `PracticeRecord` will live under
//   `lib/features/practice_records/domain/practice_record.dart` and
//   must NOT be defined here.
//
// MVP notes (DATA_MODEL_DRAFT.md §2.1, §9):
// - `practiceTagsJson` stores a JSON-encoded list of PracticeTag enum
//   names (e.g. `'["tuner","single_note"]'`). Repository layer (T013.2+)
//   is responsible for parsing / serialising.
// - `selfAssessment` stores the *string* form of a self-assessment enum
//   (`"good"` / `"neutral"` / `"needsImprovement"`). T013.1 deliberately
//   uses a `text()` column (not an enum-typed column) because
//   `SelfRating`/`SelfAssessment` naming is still under Chief Architect
//   review; Repository layer is the single place to convert enum ↔
//   string (per task brief: "映射规则留给后续 Repository 任务").
// - `audioFilePath` is nullable. T013.1 does NOT save real audio files
//   (task constraint) and T013.1 leaves the column nullable so the
//   detail page can hide playback UI without a separate schema change.
//
// schemaVersion = 1. No migration needed yet; T013.1 explicitly avoids
// stuffing unused `TODO(T005+)` stubs in `MigrationStrategy`.

import 'package:drift/drift.dart';

@DataClassName('PracticeRecordData')
class PracticeRecords extends Table {
  /// UUID v4, primary key. Generated by Repository layer, not by the
  /// database, so callers can build records before insert.
  TextColumn get id => text()();

  /// Local-date of the practice session, normalised to local midnight
  /// (see `core/utils/practice_day_calculator.dart`). Stored as
  /// `INTEGER` (unix seconds) for indexability.
  DateTimeColumn get practiceDate => dateTime()();

  /// 1-based day index in the 7-day cycle (1..7).
  IntColumn get dayIndex => integer()();

  /// Name of the `PracticeType` enum case. Stored as the enum name
  /// string so future enum re-orderings do not shift data.
  TextColumn get primaryPracticeType => text()();

  /// JSON-encoded list of `PracticeTag` enum names.
  TextColumn get practiceTagsJson => text()();

  /// Human-readable description of what the user practised.
  TextColumn get practiceContent => text()();

  /// Total practice duration in seconds (>= 0).
  IntColumn get durationSeconds => integer()();

  /// Whether the user marked the session as completed.
  BoolColumn get isCompleted => boolean().withDefault(const Constant(false))();

  /// Name of the `SelfAssessment` enum case, or `null` if the user
  /// skipped self-assessment. Stored as the enum name string.
  TextColumn get selfAssessment => text().nullable()();

  /// Relative path to the recording file under the app private dir, or
  /// `null` if no recording is attached. T013.1: always `null` in
  /// practice (no audio is saved yet), but the column is nullable so
  /// T013.5+ can populate it without a schema change.
  TextColumn get audioFilePath => text().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => {id};
}
